#!/bin/bash
# Gaussian zeros and ones comparison
#./main.o input/input-brokentop.txt 240 320 4 5 0 0 output-gaussian-zeros-x10.txt
#./main.o input/input-brokentop.txt 240 320 4 5 0 0 output-gaussian-ones-x10.txt
#./main.o input/input-brokentop.txt 240 320 4 5 0 0 output-gaussian-ones-x100.txt
#./main.o input/input-brokentop.txt 240 320 4 5 0 0 output-gaussian-ones-ints.txt

#./GetPixels.o 2 output-gaussian-zeros-x10.png output-gaussian-zeros-x10.txt 240 320
#./GetPixels.o 2 output-gaussian-ones-x10.png output-gaussian-ones-x10.txt 240 320
#./GetPixels.o 2 output-gaussian-ones-x100.png output-gaussian-ones-x100.txt 240 320
#./GetPixels.o 2 output-gaussian-ones-ints.png output-gaussian-ones-ints.txt 240 320

# Gaussian separable

./main.o input/input-brokentop.txt 240 320 4 5 0 0 output-gaussian-full2.txt
./main.o input/input-brokentop.txt 240 320 2 5 0 0 output-gaussian-x2.txt
./main.o input/input-brokentop.txt 240 320 3 5 0 0 output-gaussian-y2.txt
./main.o input/input-brokentop.txt 240 320 2 5 3 5 output-gaussian-xy2.txt

./GetPixels.o 2 output-gaussian-full2.png output-gaussian-full2.txt 240 320
./GetPixels.o 2 output-gaussian-x2.png output-gaussian-x2.txt 240 320
./GetPixels.o 2 output-gaussian-y2.png output-gaussian-y2.txt 240 320
./GetPixels.o 2 output-gaussian-xy2.png output-gaussian-xy2.txt 240 320

