#!/bin/bash

./main.o input/input-rabbit.txt 100 100 4 3 0 0 kernel-delta.txt
./GetPixels.o 2 kernel-delta.png kernel-delta.txt 100 100

./main.o input/input-rabbit.txt 100 100 4 3 0 0 kernel-edge1.txt
./GetPixels.o 2 kernel-edge1.png kernel-edge1.txt 100 100

./main.o input/input-rabbit.txt 100 100 4 3 0 0 kernel-edge2.txt
./GetPixels.o 2 kernel-edge2.png kernel-edge2.txt 100 100

./main.o input/input-rabbit.txt 100 100 4 3 0 0 kernel-edge3.txt
./GetPixels.o 2 kernel-edge3.png kernel-edge3.txt 100 100

./main.o input/input-rabbit.txt 100 100 4 3 0 0 kernel-blur1.txt
./GetPixels.o 2 kernel-blur1.png kernel-blur1.txt 100 100

./main.o input/input-rabbit.txt 100 100 4 3 0 0 kernel-blur1a.txt
./GetPixels.o 2 kernel-blur1a.png kernel-blur1a.txt 100 100

./main.o input/input-rabbit.txt 100 100 4 3 0 0 kernel-blur2.txt
./GetPixels.o 2 kernel-blur2.png kernel-blur2.txt 100 100

./main.o input/input-rabbit.txt 100 100 4 3 0 0 kernel-blur2a.txt
./GetPixels.o 2 kernel-blur2a.png kernel-blur2a.txt 100 100

./main.o input/input-rabbit.txt 100 100 4 3 0 0 kernel-sharp.txt
./GetPixels.o 2 kernel-sharp.png kernel-sharp.txt 100 100



